{% set name = "websockets-cli" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0b2e729cee65f67406840a502cd915ee5ecb450849517be2470e61d180129343

build:
  entry_points:
    - ws = ws.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - trio-websocket >=0.11.1,<0.12.0
    - rich >=13.7.0,<14.0.0
    - pydantic >=2.5.0,<3.0.0
    - tomli >=2.0.1,<3.0.0
    - certifi >=2023.11.17,<2024.0.0
    - click-didyoumean >=0.3.0,<0.4.0
    - shellingham >=1.5.0,<2.0.0
    - prompt-toolkit >=3.0.41,<4.0.0
    - pydantic-settings >=2.1.0,<3.0.0

test:
  imports:
    - ws
  commands:
    - pip check
    - ws --help
  requires:
    - pip

about:
  home: https://github.com/lewoudar/ws
  doc_url: https://pyws.readthedocs.io
  summary: A simple yet powerful websocket cli
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
